### ISSUE TITLE
Throwing Null Pointer Exception

### ISSUE THREAD

**Issue by rajgajjar27** [ColdTea-Projects/SmplrAlarm#15]
2023-07-18 11:55:43.598 28100-29273/com.app E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.app, PID: 28100
    java.lang.NullPointerException: Parameter specified as non-null is null: method com.app.utils.SmplrAlarm.repository.relations.AlarmNotifications.<init>, parameter notificationEntity
        at com.app.utils.SmplrAlarm.repository.relations.AlarmNotifications.<init>(Unknown Source:12)
        at com.app.utils.SmplrAlarm.repository.dao.DaoAlarmNotification_Impl$11.call(DaoAlarmNotification_Impl.java:360)
        at com.app.utils.SmplrAlarm.repository.dao.DaoAlarmNotification_Impl$11.call(DaoAlarmNotification_Impl.java:303)
        at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:88)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.kt:36)
        at androidx.room.TransactionExecutor.$r8$lambda$AympDHYBb78s7_N_9gRsXF0sHiw(Unknown Source:0)
        at androidx.room.TransactionExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@622586e, Dispatchers.IO]

**Comment by chiragtalaviya** [comment]
Same here:

Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method hi.a.<init>, parameter notificationChannelEntity
       at de.coldtea.smplr.smplralarm.repository.relations.AlarmNotifications.<init>(AlarmNotifications.kt:8)
       at de.coldtea.smplr.smplralarm.repository.dao.DaoAlarmNotification_Impl$11.call(DaoAlarmNotification_Impl.java:368)
       at de.coldtea.smplr.smplralarm.repository.dao.DaoAlarmNotification_Impl$11.call(DaoAlarmNotification_Impl.java:307)
       at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:88)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:47)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by rajgajjar27** [comment]
Any update ?

**Comment by talha970** [comment]
any update?
